import {createScene} from './scene.js';

// Throwaway visual study. Five alternatives, never mounted on the public homepage.
const $=s=>document.querySelector(s);
const variants={
 A:{title:'Everything you love.<br><span>Coming together.</span>',description:'All your shows. All your services. One place to make sense of them.',middle:'A home for all of it.',end:'Your next watch.<br><span>Beautifully in order.</span>'},
 B:{title:'Your streaming universe.<br><span>One centre.</span>',description:'Bring the shows you follow and the services you use into the same orbit.',middle:'Everything revolves around you.',end:'Less searching.<br><span>More looking forward.</span>'},
 C:{title:'So much to watch.<br><span>Find your sequence.</span>',description:'Turn an endless stream of possibilities into a watchlist that makes sense.',middle:'Let Seasons put it together.',end:'One show.<br><span>Then the next.</span>'},
 D:{title:'Make room for<br><span>what you love.</span>',description:'Your shows, your services, and a little space to plan what comes next.',middle:'A place for every favourite.',end:'Everything.<br><span>In its place.</span>'},
 E:{title:'Get lost in the stories.<br><span>Find your way here.</span>',description:'Step through the noise. Bring your entertainment into focus with Seasons.',middle:'It all comes into focus.',end:'Your watchlist.<br><span>A clearer picture.</span>'}
};
let variant=new URLSearchParams(location.search).get('variant')?.toUpperCase()||'A';
if(!variants[variant])variant='A';
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let scene,data,items=[],pending=false,phase=-1;
function setVariant(value){variant=value;document.body.dataset.variant=value;$('#variant').value=value;const url=new URL(location.href);url.searchParams.set('variant',value);history.replaceState(null,'',url);phase=-1;render();console.info('Prototype state',{variant,concept:$('#variant').selectedOptions[0].text,reducedMotion:reduced});}
function cycle(step){const keys=Object.keys(variants);setVariant(keys[(keys.indexOf(variant)+step+5)%5]);}
function progress(){return Math.max(0,Math.min(1,scrollY/Math.max(1,$('#journey').offsetHeight-innerHeight)));}
function render(){pending=false;const p=reduced?1:progress(),v=variants[variant];const next=p<.31?0:p<.61?1:2;if(next!==phase){phase=next;$('h1').innerHTML=phase===0?v.title:phase===1?v.middle:v.end;$('#description').textContent=phase===0?v.description:phase===1?'Follow what you love. Seasons brings your watchlist and subscriptions together.':'See what you want to watch. Plan when each subscription is worth keeping.';$('#phase-label').textContent=['Gather your favourites','Bring them into Seasons','Build your watch plan'][phase];$('#phase-count').textContent=`0${phase+1} / 03`;}
 $('.rail i').style.width=`${p*100}%`;scene?.update(p,variant);window.prototypeState={variant,progress:p,phase,reducedMotion:reduced,renderer:scene?'three.js':'static',shows:data?.shows.length||0};}
function schedule(){if(!pending){pending=true;requestAnimationFrame(render);}}
function staticScene(){const box=document.createElement('div');box.className='static-scene';const logo=document.createElement('img');logo.src='../../seasonslogo.png';logo.alt='Seasons';logo.className='static-logo';box.append(logo);items.slice(0,12).forEach(item=>{const img=document.createElement('img');img.src=item.image;img.alt=item.title;img.className=item.kind;box.append(img);});$('#scene').replaceChildren(box);}
async function setupScene(){scene?.dispose();scene=null;$('#scene').replaceChildren();document.body.classList.toggle('reduced',reduced);$('#motion').setAttribute('aria-pressed',String(reduced));$('#motion').textContent=reduced?'Enable motion':'Reduce motion';if(reduced){staticScene();render();return;}try{scene=await createScene($('#scene'),items,'../../seasonslogo.png');}catch(error){console.warn('Three.js unavailable; showing static artwork.',error);staticScene();}render();}
function catalog(){const grid=$('#catalog');grid.replaceChildren();data.shows.slice(0,12).forEach(show=>{const card=document.createElement('a');card.className='show';card.href=`https://www.themoviedb.org/tv/${show.id}`;card.target='_blank';card.rel='noopener';const img=document.createElement('img');img.src=show.poster;img.alt=show.title;img.loading='lazy';const title=document.createElement('h4');title.textContent=show.title;const rank=document.createElement('p');rank.textContent=`Trending · ${show.rank}`;card.append(img,title,rank);grid.append(card);});const age=Date.now()-new Date(data.updatedAt).getTime();$('#freshness').textContent=`${age>86400000?'Saved selection':'Updated'} ${new Date(data.updatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})} · TMDB`;
 items=[];data.shows.slice(0,12).forEach((s,i)=>{items.push({title:s.title,image:s.poster,kind:'show'});if(i%2===0&&data.providers[i/2]){const n=data.providers[i/2];items.push({title:n.name,image:n.logo,kind:'provider'});}});}
$('#previous').onclick=()=>cycle(-1);$('#next').onclick=()=>cycle(1);$('#variant').onchange=e=>setVariant(e.target.value);$('#replay').onclick=()=>scrollTo({top:0,behavior:'instant'});$('#motion').onclick=async()=>{reduced=!reduced;await setupScene();};document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable]'))return;if(e.key==='ArrowLeft'){e.preventDefault();cycle(-1);}if(e.key==='ArrowRight'){e.preventDefault();cycle(1);}});addEventListener('scroll',schedule,{passive:true});addEventListener('resize',()=>{scene?.resize();schedule();});setVariant(variant);
try{data=await fetch('./data.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json();});catalog();await setupScene();}catch(error){$('#freshness').textContent='Artwork could not load. Reload to try again.';console.error(error);}
